name: Setup node

inputs:
  node_version:
    description: Node.js version
    required: true

runs:
  using: composite
  steps:
    - name: Setup Node.js (v: ${{ inputs.node_version }})
      uses: actions/setup-node@v3.5.0
      with:
        node-version: ${{ inputs.node_version }}

    - name: Cache node_modules
      uses: actions/cache@v2
      id: cache
      with:
        path: node_modules
        key: ${{ runner.os }}-modules-${{ hashFiles('package-lock.json') }}

    - name: Install dependencies
      if: steps.cache.outputs.cache-hit != 'true'
      run: npm install
