frameworkVersion: '^3.3.0'
service: ${env:COMMON_APP_NAME, 'exampleAppCommon'}
useDotenv: true
plugins:
  - serverless-step-functions
  - serverless-webpack
  - serverless-offline
  - serverless-plugin-log-retention

package:
  individually: true

custom:
  seed:
    incremental:
      enabled: true
  accountId: ${env:ACCOUNT_ID}
  logRetentionInDays: 30
  webpack:
    webpackConfig: "webpack.config.js"
    packager: "npm"
  stepFunctionsLocal:
    accountId: ${env:ACCOUNT_ID}
    region: us-east-1
  inputBucketName: tsh-academy-serverless-workshops-input-bucket-${self:provider.stage}
  extractedFilesBucketName: tsh-academy-serverless-workshops-extracted-files-${self:provider.stage}
provider:
  name: aws
  runtime: nodejs14.x
  region: ${env:AWS_LAMBDAS_REGION, 'eu-west-1'}
  stage: ${opt:stage, 'dev'}
  memorySize: 256
  timeout: 30
  environment:
    APP_NAME: ${env:APP_NAME, 'tshAcademySlsWorkshops'}
    AWS_LAMBDAS_REGION: ${env:AWS_LAMBDAS_REGION, 'eu-west-1'}
    DDB_TABLE_NAME: ${self:service}-test-ddb-table-${self:provider.stage}

resources:
  Outputs:
    ScanCvWorkflowStateMachine:
      Description: Scan CV workflow state machine Arn
      Value:
        Ref: ScanCvWorkflow${self:service}${opt:stage, 'dev'}
    ApiUri:
      Value: !GetAtt HttpApi.ApiEndpoint # !Sub "https://${HttpApi}.execute-api.${self:provider.region}.amazonaws.com/${self:provider.stage}/"
  Resources:
    scanSnsTopic:
      Type: AWS::SNS::Topic
      Properties:
        TopicName: ${self:service}ScanFailedTopic${self:provider.stage}
    inputBucket:
      Type: AWS::S3::Bucket
      Properties:
        BucketName: ${self:custom.inputBucketName}
    extractedFilesBucket:
      Type: AWS::S3::Bucket
      Properties:
        BucketName: ${self:custom.extractedFilesBucketName}
    ScanCvWorkflowStateMachineRole: ${file(workflows/scan-cv-workflow/workflow.iam.yml)}
    SomeDynamoDbTable:
      Type: AWS::DynamoDB::Table
      Properties:
        TableName: ${self:provider.environment.DDB_TABLE_NAME}
        AttributeDefinitions:
          - AttributeName: pk
            AttributeType: S
          - AttributeName: sk
            AttributeType: S
        KeySchema:
          - AttributeName: pk
            KeyType: HASH
          - AttributeName: sk
            KeyType: RANGE
        BillingMode: PAY_PER_REQUEST
    CognitoUserPool:
      Type: AWS::Cognito::UserPool
      Properties:
        UserPoolName: UserPool${self:service}${opt:stage, 'dev'}
        Schema:
          - AttributeDataType: String
            Name: email
            Required: False
            Mutable: True
          - AttributeDataType: String
            Name: phone
            Required: false
            Mutable: False
          - AttributeDataType: String
            Name: msalIdToken
            Required: false
            Mutable: True
        AutoVerifiedAttributes:
          - email
        UsernameConfiguration:
          CaseSensitive: False
        UsernameAttributes:
          - email
        Policies:
          PasswordPolicy:
            MinimumLength: 8
            RequireLowercase: True
            RequireUppercase: True
            RequireNumbers: True
            RequireSymbols: False
        AccountRecoverySetting:
          RecoveryMechanisms:
            - Name: verified_email
              Priority: 1
        EmailConfiguration:
          EmailSendingAccount: COGNITO_DEFAULT
        VerificationMessageTemplate:
          DefaultEmailOption: CONFIRM_WITH_LINK
