on:
  workflow_call:
    outputs: 
      stage:
        value: ${{ jobs.get-stage-name.outputs.stage }}
        description: Name of the stage to deploy to, created on top of PR number

jobs:
  get-stage-name:
    runs-on: ubuntu-latest
    name: Get stage name
    outputs:
      stage: ${{ steps.get-stage-name.outputs.stage }}

    steps:
      - uses: actions/checkout@v3

      - name: Retrieve pull request number
        id: get-stage-name
        run: |
          echo stage=pr${{ github.event.number }} >> $GITHUB_OUTPUT
        shell: bash
