name: Delete per-feature environment

on:
  pull_request:
    types: [closed]

env:
  NODE_VERSION: 16
  APP_ENV: dev

jobs:
  delete-per-feature-environment:
    runs-on: ubuntu-latest
    name: Delete per-feature environment

    steps:
      - uses: actions/checkout@v3

      - name: Get stage name
        id: get-stage-name
        uses: ./.github/actions/get-stage-name

      - name: Setup node
        uses: ./.github/actions/setup-node
        with:
          node_version: ${{ env.NODE_VERSION }}

      - name: Remove stack with stage ${{ steps.get-stage-name.outputs.stage }}
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.DEV_AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.DEV_AWS_SECRET_ACCESS_KEY }}
          AWS_DEFAULT_REGION: ${{ vars.DEV_AWS_DEFAULT_REGION }}
          ACCOUNT_ID: ${{ vars.DEV_AWS_ACCOUNT_ID }}
          APP_ENV: ${{ env.APP_ENV }}
        run: |
          npx sls remove --stage ${{ steps.get-stage-name.outputs.stage }} --verbose

      - name: Deactivate environment
        uses: bobheadxi/deployments@v1.2.0
        with:
          step: delete-env
          env: ${{ steps.get-stage-name.outputs.stage }}
          ref: ${{ github.head_ref }}
