name: Create per-feature environment

on:
  pull_request:
    types: [opened, synchronize, reopened]

jobs:
  install-dependencies:
    runs-on: ubuntu-latest
    name: Install dependencies
    id: install-dependencies
    strategy:
      matrix:
        node-version: [16]

    steps:
      - uses: actions/checkout@v3

      - name: Install dependencies
        run: npm run install

      - name: Run linter
        run: npm run lint

      - name: Run unit tests
        run: npm run test:unit

  create-per-feature-environment:
    runs-on: ubuntu-latest
    name: Create per-feature environment
    id: create-per-feature-environment
    depends-on: [install-dependencies]
    strategy:
      matrix:
        node-version: [16]

    steps:
      - name: Install dependencies
        run: npm run install

      - name: Deploy to stage ${{ github.event.pull_request.head.ref }}
#        env:
#          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
#          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        run: npx sls deploy --stage ${{ github.event.pull_request.head.ref }}
