name: Create per-feature environment

on:
  pull_request:
    types: [opened, synchronize, reopened]

jobs:
  run-linter-and-unit-tests:
    runs-on: ubuntu-latest
    name: Run linter and unit tests

    steps:
      - uses: actions/checkout@v3

      - name: Setup node
        uses: ./.github/actions/setup-node
        with:
          node_version: 16

      - name: Run linter
        run: npm run lint

      - name: Run unit tests
        run: npm run test:unit

  retrieve-pr-number:
    uses: ./.github/workflows/retrieve-pr-number.yml

  create-per-feature-environment:
    runs-on: ubuntu-latest
    name: Create per-feature environment
    needs: [run-linter-and-unit-tests, retrieve-pr-number]

    steps:
      - uses: actions/checkout@v3

      - name: Setup node
        uses: ./.github/actions/setup-node
        with:
          node_version: 16

      - name: Deploy to stage ${{ needs.retrieve-pr-number.outputs.pr_number }}
        id: deploy
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          AWS_DEFAULT_REGION: ${{ vars.AWS_DEFAULT_REGION }}
          ACCOUNT_ID: ${{ vars.ACCOUNT_ID }}
        run: | 
          npx sls deploy --stage ${{ needs.retrieve-pr-number.outputs.pr_number }}
