name: Tests & Linter

on: [push]

jobs:
  tests:
    runs-on: ubuntu-latest
    name: Build
    strategy:
      matrix:
        node-version: [16]

    steps:
      - uses: actions/checkout@v3
      - run: cp .env.dist .env
      - run: npm install
      - run: npm run lint
      # - run: npm run tests
